#!/bin/bash

/usr/bin/figlet immudex;
echo;
echo "-= Today is: $(date) =-";
cpuIdle=$(vmstat | tail -1 | awk '{printf $15}');
cpuUsage=$((100 - $cpuIdle));
echo -e "-=\tCPU: ${cpuUsage}%\t\t\t=-";
echo -e "-=\tMEM: $(free -h | sed -n '2p' | awk '{printf $7}' | sed 's/i//') Free\t\t\t=-"; 
diskSize=$(df -h | grep '/dev/mapper' | head -1 | awk '{printf $2}');
diskFree=$(df -h | grep '/dev/mapper' | head -1 | awk '{printf $4}');
diskUsage_perc=$(df -h | grep '/dev/mapper' | head -1 | sed 's/%//' | awk '{printf $5}');
#FCP = First Crypt Partition
echo -e "-=\tFCP: ${diskFree}/${diskSize} (${diskUsage_perc}%)\t\t=-";
echo -e "-=\tPROCESSES: $(grep 'proces' /proc/stat | awk '{printf $2}')\t\t\t=-";
echo -e "-=\tUPTIME: $(uptime | awk '{printf $3}' | sed 's/,//')\t\t\t=-";
echo -e "-=\t$(uptime | grep -o "load.*$" | tr [a-z] [A-Z])\t=-";
echo -e "-= morketsmerke.net @ 2022 https://github.com/xf0r3m/immudex =-";
echo;
/usr/local/bin/immudex_upgrade --check --print
echo "====================================================================";
