#!/bin/bash

file=$1;

PS3="Link: ";
linkNames=$(cut -d ":" -f 1 $1 | sed 's/\ /_/g' | awk '{printf $1" "}')
select name in $linkNames; do
  if [ ! "$name" ]; then break; fi
  linkName=$(echo $name | sed 's/_/\ /g');
  link=$(grep "$linkName" $file | cut -d ":" -f 2-);
  if echo $link | grep -q "youtube"; then
    ytplay -a $link -f best[height=360];
  else
    mpv --no-video $link;
  fi
done
