#!/bin/bash

/usr/bin/figlet immudex;
echo;
echo "Today is: $(date)";
echo;
echo "System summary: ";
cpuIdle=$(vmstat | tail -1 | awk '{printf $15}');
cpuUsage=$((100 - $cpuIdle));
echo -e "  \tCPU: ${cpuUsage}%";
echo -e "  \tMEM: $(free -h | sed -n '2p' | awk '{printf $7}' | sed 's/i//') Free";
if $(df -h 2> /dev/null | grep -q '/dev/mapper'); then
  i=1;
  echo -e "  \tCRYPT_PARTi: Free/Total (Usage%)";
  amountOfDisks=$(df -h 2> /dev/null | grep '/dev/mapper' | wc -l | awk '{printf $1}');
  while [ $i -le $amountOfDisks ]; do
    diskSize=$(df -h 2> /dev/null | grep '/dev/mapper' | sed -n "${i}p" | awk '{printf $2}');
    diskFree=$(df -h 2> /dev/null | grep '/dev/mapper' | sed -n "${i}p" | awk '{printf $4}');
    diskUsage_perc=$(df -h 2> /dev/null | grep '/dev/mapper' | sed -n "${i}p" | sed 's/%//' | awk '{printf $5}');
  #FCP = First Crypt Partition
    echo -e "  \tCRYPT_PART${i}: ${diskFree}/${diskSize}   (${diskUsage_perc}%)";
    i=$((i + 1));
  done
else
  echo -e "  \tCRYPT_PART: N/A";
fi
echo -e "  \tPROCESSES: $(ps -aux | wc -l | awk '{printf $1}')";
utime=$(uptime | awk '{printf $3}' | sed 's/,//');
if $(echo $utime | grep -q ":"); then
  echo -e "  \tUPTIME: ${utime}";
else
  echo -e "  \tUPTIME: 0:${utime}";
fi
echo -e " \t$(uptime | grep -o "load.*$" | tr [a-z] [A-Z])";
echo;
echo -e "morketsmerke.net @ 2023 https://github.com/xf0r3m/immudex";
echo;
/usr/local/bin/immudex_upgrade --check --print;
if [ $? -ne 0 ]; then
       echo -e "\e[31mThere is no internet connection or internal error.\e[0m";
  if [ -f /tmp/feed.xml ] && [ ! -s /tmp/feed.xml ]; then
    rm -f /tmp/feed.xml;
  fi
else
  if [ "$USER" = "xf0r3m" ]; then
    sudo apt update > /tmp/update.log 2>&1 && tail -1 /tmp/update.log;
  fi
fi       
echo "====================================================================";
