#!/bin/bash

vendor=$(hostnamectl | grep 'Vendor' | awk '{printf $3}')
modelLine=$(hostnamectl | grep 'Model' | awk '{printf $3}')
model=$(hostnamectl | grep 'Model' | awk '{printf $4}')

case $vendor in
  "Lenovo") vendorShort="l";;
  "Dell") vendorShort="d";;
  *) hName="immudex";;
esac

case $modelLine in
  "ThinkPad") mLShort="TP";;
  "Latitude") mLShort="Lat";;
  *) hName="immudex";;
esac

if [ ! "$hName" ]; then
  hName="${vendorShort}-${mLShort}-$model"
  sudo hostnamectl set-hostname $hName;
  sudo sed -i "s/immudex/${hName}/" /etc/hosts;
  echo $hName | sudo tee /etc/hostname > /dev/null;
fi

