#!/bin/bash

dhclient;

if [ ! -d /boot ]; then
	mkdir /boot;
	apt purge linux-image* --purge -y;
	apt install linux-image-amd64;
fi

cp -vv /etc/apt/sources.list /etc/apt/sources.list.d/iwlwifi.list;
sed -e 's/main/contrib non-free non-free-firmware/g' -i /etc/apt/sources.list.d/iwlwifi.list;

apt update;
apt install firmware-iwlwifi;

rm /etc/apt/sources.list.d/iwlwifi.list;
apt update;

apt-get autoclean;
apt-get autoremove;
apt-get clean;
apt-get clean;


