#!/bin/bash

baseVersion=$(head -1 /etc/apt/sources.list | awk '{print $3}')

wget https://dev.mysql.com/get/mysql-apt-config_0.8.25-1_all.deb;
dpkg -i mysql-apt-config_0.8.25-1_all.deb;

sed -i "s/$baseVersion/bullseye/g" /etc/apt/sources.list;

apt update;
apt install mysql-server -y
apt-mark hold libmecab2 libssl1.1 mecab-ipadic mecab-ipadic-utf8 mecab-utils mysql-client mysql-common mysql-community-client mysql-community-client-core mysql-community-client-plugins mysql-community-server mysql-community-server-core

sed -i "s/bullseye/$baseVersion/g" /etc/apt/sources.list; 
apt update
apt install apache2 libapache2-mod-php php php-mysql -y;

apt autoremove;
apt autoclean;
apt clean;
apt clean;

rm mysql-apt-config_0.8.25-1_all.deb;
rm $0;
