#!/bin/bash

if [ "$1" ]; then
  case $1 in
    "install") echo "Installation $(basename $0) addon...";
                if [ ! -d /usr/share/immudex_addons ]; then
                  mkdir /usr/share/immudex_addons;
                fi
                cat >> $(basename $0)_installer << EOF
apt update;
apt install -y libdbus-1-dev libncursesw5-dev libpulse-dev libssl-dev libxcb1-dev libxcb-render0-dev libxcb-shape0-dev libxcb-xfixes0-dev
wget https://ftp.morketsmerke.org/immudex/testing/addons/ncspot-bin-0.13.1.tar.gz -O /tmp/ncspot-bin-0.13.1.tar.gz;
tar -xzvf /tmp/ncspot-bin-0.13.1.tar.gz -C /usr/local/bin;
rm /tmp/ncspot-bin-0.13.1.tar.gz;
EOF
                bash $(basename $0)_installer;
                if [ $? -eq 0 ]; then
                  rm $(basename $0)_installer;
                  echo $(basename $0) | tee -a /usr/share/immudex_addons/installed_addons;
                  echo "Installation $(basename $0) addon...[ OK ]";
                fi;;
    "remove") echo "Removing $(basename $0) addon...";
                cat >> $(basename $0)_uninstaller << EOF
apt remove -y libdbus-1-dev libncursesw5-dev libpulse-dev libssl-dev libxcb1-dev libxcb-render0-dev libxcb-shape0-dev libxcb-xfixes0-dev;
rm /usr/local/bin/ncspot;
EOF
                bash $(basename $0)_uninstaller;
                if [ $? -eq 0 ]; then
                  rm $(basename $0)_uninstaller;
                  sed -i "s/$(basename $0)//g" /usr/share/immudex_addons/installed_addons;
                  echo "Removing $(basename $0) addon...[ OK ]";
                fi;;
  esac
else
  echo "Internal error: action must be given.";
  exit 1;
fi
