#!/bin/bash

if [ "$1" ]; then
  case $1 in
    "install") echo "Installation $(basename $0) addon...";
                if [ ! -d /usr/share/immudex-addons ]; then
                  mkdir /usr/share/immudex-addons;
                fi
                cat >> $(basename $0)_installer << EOF
VERSION="0.13.4";
ARCH="\$(uname -m)";
if [ ! -x /usr/bin/curl ]; then apt install -y curl; fi
curl https://ftp.morketsmerke.org/immudex/testing/addons/ncspot-bin-\${VERSION}-\${ARCH}.tar.gz | tar -xzf - -C /usr/local/bin;
chmod +x /usr/local/bin/ncspot;
EOF
                bash $(basename $0)_installer;
                if [ $? -eq 0 ]; then
                  rm $(basename $0)_installer;
                  echo $(basename $0) | tee -a /usr/share/immudex-addons/installed-addons;
                  echo "Installation $(basename $0) addon...[ OK ]";
                fi;;
    "remove") echo "Removing $(basename $0) addon...";
                cat >> $(basename $0)_uninstaller << EOF
rm /usr/local/bin/ncspot;
EOF
                bash $(basename $0)_uninstaller;
                if [ $? -eq 0 ]; then
                  rm $(basename $0)_uninstaller;
                  sed -i "s/$(basename $0)//g" /usr/share/immudex-addons/installed-addons;
                  echo "Removing $(basename $0) addon...[ OK ]";
                fi;;
  esac
else
  echo "Internal error: action must be given.";
  exit 1;
fi
