#!/bin/bash

if [ "$1" ]; then
  case $1 in
    "install") echo "Installation $(basename $0) addon...";
                if [ ! -d /usr/share/immudex-addons ]; then
                  sudo mkdir /usr/share/immudex-addons;
                fi
                cat >> $(basename $0)_installer << EOF
VERSION="0.87.1";
ARCH="\$(uname -m)";
if [ ! -x /usr/bin/curl ]; then apt install -y curl; fi
mkdir -p /usr/share/fonts/truetype/meslo;
curl -L https://github.com/ryanoasis/nerd-fonts/releases/download/v3.0.2/Meslo.tar.xz | tar -xJf - -C /usr/share/fonts/truetype/meslo;
curl https://ftp.morketsmerke.org/immudex/testing/addons/nu-bin-\${VERSION}-\${ARCH}.tar.gz | tar -xzf - -C /usr/local/bin;
chmod +x /usr/local/bin/nu;
wget https://ohmyposh.dev/install.sh -O /tmp/oh-my-posh-install.sh;
bash /tmp/oh-my-posh-install.sh;
rm /tmp/oh-my-posh-install.sh;
chmod +x /usr/local/bin/oh-my-posh;
mkdir /usr/share/oh-my-posh;
mv /root/.cache/oh-my-posh/themes /usr/share/oh-my-posh;
wget https://github.com/xf0r3m/immudex-testing/raw/main/files/immudex-nu.omp.json -O /usr/share/oh-my-posh/immudex-nu.omp.json;
EOF
                bash $(basename $0)_installer;
                if [ $? -eq 0 ]; then
                  rm $(basename $0)_installer;
                  echo $(basename $0) | sudo tee -a /usr/share/immudex-addons/installed-addons;
                  echo "Installation $(basename $0) addon...[ OK ]";
                fi;;
    "remove") echo "Removing $(basename $0) addon...";
                cat >> $(basename $0)_uninstaller << EOF
rm -rf /usr/share/fonts/truetype/meslo;
rm /usr/local/bin/nu;
rm /usr/local/bin/oh-my-posh;
rm -rf /usr/share/oh-my-posh;
EOF
                bash $(basename $0)_uninstaller;
                if [ $? -eq 0 ]; then
                  rm $(basename $0)_uninstaller;
                  sudo sed -i "s/$(basename $0)//g" /usr/share/immudex-addons/installed-addons;
                  echo "Removing $(basename $0) addon...[ OK ]";
                fi;;
  esac
else
  echo "Internal error: action must be given.";
  exit 1;
fi
