#!/bin/bash

dhclient;
cd;
if [ -x /usr/bin/git ]; then git clone https://github.com/xf0r3m/immudex-testing;
else apt install git && git clone https://github.com/xf0r3m/immudex-testing;
fi

source ~/immudex-testing/versions/template.sh

if [ ! -d /boot ]; then
	mkdir /boot;
	apt purge linux-image* --purge -y;
	apt install linux-image-amd64;
fi

cp -vv /etc/apt/sources.list /etc/apt/sources.list.d/nvidia.list;
sed -e 's/bookworm/bullseye/g' -e 's/main/contrib non-free/g' -i /etc/apt/sources.list.d/nvidia.list;
apt update;
apt install build-essential dkms linux-headers-$(uname -r);
apt install nvidia-detect
apt install nvidia-driver

apt remove libxnvctrl0 -y;
sed -i 's/bookworm/bullseye/g' /etc/apt/sources.list;
apt update;
apt install libxnvctrl0 -y
sed -i 's/bullseye/bookworm/g' /etc/apt/sources.list;
apt install xfce4-sensors-plugin xfce4-goodies nvidia-settings;

tidy;
