#!/bin/bash

set -e

source library.sh

RED="\e[31m";
GREEN="\e[32m";
YELLOW="\e[33m";
ENDCOLOR="\e[0m";
root="/run/live/medium";

function help() {
  echo "immudex-upgrade - script for searching upgrades and upgrade immudex";
  echo "@ 2023 morketsmerke.org";
  echo "Options:";
  echo " --check - check there are upgrades for immudex";
  echo " --upgrade - upgrade immudex from given source";
}

if [ "$1" ]; then
  if [ "$1" ] && [ "$1" = "--check" ]; then
    if check_distro_commit; then 
      echo -e "${GREEN}This${ENDCOLOR} is the latest version of immudex";
    else
      echo -e "There is a ${RED}new${ENDCOLOR} version of immudex:";
      echo "===================================================";
      check_distro_commit --print;
    fi
  elif [ "$1" ] && [ "$1" = "--upgrade" ]; then
    part=$(sudo blkid | grep 'LABEL="immudex"' | awk '{printf $1}' | cut -d ":" -f 1);
    if sudo mount | grep -q "$part"; then
      echo -n "Mounting iso image...";
      sudo mount $2 /mnt > /dev/null 2>&1;
      if [ $? -eq 0 ]; then echo -e "[ ${GREEN}OK${ENDCOLOR} ]"; fi
      mountPointList=$(sudo mount | grep "$part" | awk '{printf $3" "}');
      for mountPoint in $mountPointList; do
        echo -n "Unlocking $mountPoint ..."; 
        sudo mount $part $mountPoint -o remount,rw > /dev/null 2>&1;
        if [ $? -eq 0 ]; then
          echo -e "[ ${GREEN}OK${ENDCOLOR} ]";
        else
          echo -e "[ ${RED}FAIL${ENDCOLOR} ]";
        fi
      done
      echo "Copying immudex files to the disk...";
      sudo cp -vv /mnt/live/* ${mountPoint}/live;
    else
      echo "Mounting immudex partition...";
      sudo mount $part /mnt >> /dev/null 2>&1;
      if [ $? -eq 0 ]; then echo -e "[ ${GREEN}OK${ENDCOLOR} ]"; fi
      echo "Copying immudex files to the disk...";
      sudo cp -vv /run/live/medium/live/* /mnt/live;
    fi
    if [ $? -eq 0 ]; then
      echo -e "Copying immudex files to the disk...[ ${GREEN}OK${ENDCOLOR} ]";
    else
      echo -e "Copying immudex files to the disk...[ ${RED}FAIL${ENDCOLOR} ]";
    fi
  elif [ "$1" ] && [ "$1" = "--myversion" ]; then
    if [ -d /tmp/immudex-testing ]; then 
      (cd /tmp/immudex-testing && git pull > /dev/null 2>&1)
    else
      git clone https://github.com/xf0r3m/immudex-testing /tmp;
    fi
    (cd /tmp/immudex-testing && git show $(cat /run/live/medium/live/version))
  else
    help;
    exit 1;
  fi
else
  help;
  exit 1;
fi
